name: Test

on: [push, pull_request, workflow_dispatch]

env:
  FORCE_COLOR: 1

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
        os: [ubuntu-latest, macos-latest, windows-latest]
        parser: [lxml, stdlib]
        include:
          # Include new variables for Codecov
          - { codecov-flag: GHA_Ubuntu, os: ubuntu-latest }
          - { codecov-flag: GHA_macOS, os: macos-latest }
          - { codecov-flag: GHA_Windows, os: windows-latest }

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: "setup.py"

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install -U wheel
          python -m pip install -U pytest pytest-cov

      - name: Install lxml
        if: matrix.parser == 'lxml'
        run: |
          python -m pip install -U lxml

      - name: Test
        run: |
          python3 -m pytest test.py --cov gpxpy --cov-report xml

      - name: Upload coverage
        uses: codecov/codecov-action@v3.1.1
        with:
          flags: ${{ matrix.codecov-flag }}
          name: ${{ matrix.os }} Python ${{ matrix.python-version }}
